### ISSUE TITLE
Randomly Losing the Server Stream

### ISSUE THREAD

**Issue by TheDerpySage** [mvarhola/comfy-channel#6]
Running on Ubuntu 18 VM, vendor ffmpeg.

I am for whatever reason losing the server stream within 15 minutes of running. I'm not sure if it's because I'm using a VM but randomly I will lose the server stream, and the HLS stream will die. It also starts to hang on trying to play the next video when this happens. 

I've been trying to investigate this issue for a day and I'm coming up with nothing. Without being able to see some sort of feedback from ffmpeg about why it's stopping (and the fact that I'm very new to ffmpeg), I'm having trouble finding a reason or a way to fix it. It also still awkwardly waits the duration before moving on to attempting to push the next file to the client. 

![screenshot1](https://user-images.githubusercontent.com/11201157/62734575-f37e3380-b9ee-11e9-977b-60dcd2994b76.png)

Unrelated observation; Processes that are killed by the script when they timeout aren't cleaned up properly and result in zombie processes. They are eventually cleaned up when the script exits, so I'm not sure if this is a problem or not. 

![screenshot2](https://user-images.githubusercontent.com/11201157/62734600-0133b900-b9ef-11e9-992f-215336a89f0c.png)

**Comment by mvarhola** [comment]
Thanks for opening the issue! 

For the first part, where the stream may be lost, it most likely has to do with the way that the "upnext" videos are created. Since the video and audio are taken from two different sources, sometimes they will get out of sync and fail to finish playing, causing the stream to hang. I see in your first screenshot that the upnexts are taking longer to play than expected, which there is protection code for. It should close out the upnext and move on to playing another video, but I have to see why this error is caused.

If you'd like to help me with debugging, I added two debug flags: **SERVER_DEBUG** in [Server.py](https://github.com/mvarhola/comfy-channel/blob/master/src/Server.py#L6) and **CLIENT_DEBUG** in [Client.py](https://github.com/mvarhola/comfy-channel/blob/master/src/Client.py#L10). Set one of these at a time to **True**, and the STDERR output of the corresponding ffmpeg instance will be sent back to the shell, showing any errors.

As for the processes that are not cleaned up, I'll investigate this issue.

**Comment by TheDerpySage** [comment]
I will go ahead and give this a whirl to see what i can find out. Should be able to get around to it tomorrow.

**Comment by TheDerpySage** [comment]
The stream works just fine with a fresh clone of master. (Working out of the box now!)

Not sure what was going on, but for good measure you might wanna keep those debug flags there in case we run into problems again. I was able to pull off a 30 minute stream with no complications. 

![screenshot3](https://user-images.githubusercontent.com/11201157/63126686-158b2f00-bf76-11e9-8687-22405922d5eb.png)

When processes end correctly, they don't result in zombie processes either so we should be fine there. 

![screenshot2](https://user-images.githubusercontent.com/11201157/63126704-1b811000-bf76-11e9-8db2-7de434cefab2.png)

I'll report any issues as I start testing even longer schedules.

**Comment by mvarhola** [comment]
Awesome news! Thanks for looking into it!

**Comment by tabital0** [comment]
[TheDerpySage](https://github.com/TheDerpySage) Im wondering what the full FFmpeg command is that's partially shown in this picture. I like to use this command in another program to keep it stable. thanks in advance

**Comment by TheDerpySage** [comment]
> [TheDerpySage](https://github.com/TheDerpySage) Im wondering what the full FFmpeg command is that's partially shown in this picture. I like to use this command in another program to keep it stable. thanks in advance

Sorry about the late reply, but it depends on what youre looking at the "Server" that accepts the pipe'd input, or the "Client". 
In general, if youre looking to maintain stability make sure to be adding the -re flag that makes sure either stream only outputs frames at the real framerate of whatever its consuming to avoid problems.

**Comment by TheDerpySage** [comment]
[@tabital0](https://github.com/tabital0)

Here I did a test run to get the exact commands for you with some test content on my server
Server:
```
ffmpeg -re -i pipe: -loop 1 -t 4 -i upnext/moe_scaled.png -filter_complex [0:v]drawtext=fontcolor=white:fontfile=fonts/hc-too5.ttf:fontsize=20:shadowcolor=black:shadowx=2:shadowy=2:text=%{localtime\\\\:%R}:x=25:y=25[s0];[s0][1]overlay=eof_action=repeat:x=734:y=0[s1];[s1][0:a]concat=a=1:n=1:v=1[s2] -map [s2] -f flv -acodec aac -aspect 854:480 -crf 18 -pix_fmt yuv420p -preset ultrafast -tune zerolatency -vcodec h264 rtmp://127.0.0.1/live/index
```

Client:
```
ffmpeg -re -i /mnt/Video/Youtube/Videos/theweeklyslap/'How do I start investing'-NM6tmqJil7I.mp4 -filter_complex [0:v]scale=force_original_aspect_ratio=decrease:h=480:w=854[s0];[s0]pad=h=480:w=854:x=(ow-iw)/2:y=(oh-ih)/2[s1];[s1]yadif[s2];[s2][0:a:0]concat=a=1:n=1:v=1[s3] -map [s3] -f hls -ab 168k -ac 2 -acodec aac -ar 44100 -aspect 854:480 -flags +cgop -g 25 -hls_allow_cache 0 -hls_list_size 5 -hls_time 3 -pix_fmt yuv420p -preset ultrafast -strict 1 -vcodec h264 pipe: 
```
